### ISSUE TITLE
Dragging pin marker

### ISSUE THREAD

**Issue by georgemoon** [greenstone/keadatabase-front#116]
Pete N reports

"Once I dropped the pin on the map, I couldn't drag it to the right spot at the Viaduct lookout.
I was using google chrome on a home computer."

**Comment by sgmbr** [comment]
Feature component has `draggable` option which is the only way provided by react-mapbox-gl.
https://github.com/alex3165/react-mapbox-gl/blob/master/docs/API.md#feature

Currently it's not working:
- The marker fades out when started dragging and fades in when stopped. 
- In mobile the map moves too.

**Comment by sgmbr** [comment]
Okay, mapbox-gl Marker has draggable option but react-mapbox-gl implements Marker independently and it doesn't have draggable option.
mapbox-gl symbol layer does not have draggable but react-mapbox-gl added draggable to it, and it's not working well as above.

So if we want a draggable marker we need to implement it but I don't think it's worth it.
