### ISSUE TITLE
Improvements to date/time selector

### ISSUE THREAD

**Issue by georgemoon** [greenstone/keadatabase-front#117]
Graeme K reports:

"calendar widget, time function, not that intuitive to scroll time on desktop browsers as need to hold (left-click) and move pointer to upper or lower extremities of time box. 

Windows 10 - On Firefox (v.62), if you move pointer outside the div box whilst scrolling everything highlights within, or just random stuff on page highlights, a bit messy. No time scroll available at all on IE (v.11). Chrome (v.70) only highlights date/time input when scrolling outside div, but does scroll on extremities ok. On Linux more or less the same applies on Firefox.

On my Android Tablet/Phone, widget works as expected on any browser. Keyboard triggers on entering date/time input and obscures the widget on tablet in landscape format as window scrolls to bring date/time input into focus/view (not widget), can't do much about that except to make input "readonly" and still trigger widget - that would then defeat keyboard editing. To bring widget into view must finger pull on widget only, touching browser window closes widget and you start over. When you choose a date, there is a second trigger of the widget which again scrolls window to bring input into focus/view, shows keyboard, and again widget is obscured.

Don't think there is a neat, one size fits all, solution to the time input requirement; dates are easy."

**Comment by georgemoon** [comment]
I remember struggling trying to find a good datepicker library that worked across mobile and desktop devices, not sure if there's a better option we can use here @sgmbr?

**Comment by sgmbr** [comment]
I could locally fix the desktop behaviour by fixing css to show scroll bar on the right side of the time picker. Should work on all browsers (worked on Chrome and Firefox).
For mobile, a possible solution is to use vanilla HTML input so that mobile shows date/time picker instead of keyboard.

**Comment by sgmbr** [comment]
https://caniuse.com/#feat=input-datetime
Date/time picker is well supported on mobile so if we restrict it to mobile there shouldn't be a problem.

**Comment by georgemoon** [comment]
Deployed to beta.keadatabase.nz for testing

**Comment by georgemoon** [comment]
Moved to Trello
